services:
  vpn:
    image: ghcr.io/qdm12/gluetun
    container_name: dasovbot_vpn
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
    volumes:
      - ./vpn:/gluetun
    devices:
      - /dev/net/tun
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "nslookup", "google.com", "8.8.8.8"]
      timeout: 10s
      interval: 10s
      retries: 3

  api:
    container_name: dasovbot_api
    image: ghcr.io/volkovskiyda/telegram-bot-api
    restart: always
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn

  bot:
    container_name: dasovbot
    image: ghcr.io/volkovskiyda/dasovbot
    build: .
    restart: always
    volumes:
      - ./config/:/project/config
    environment:
      - BASE_URL=${BASE_URL}
      - READ_TIMEOUT=${READ_TIMEOUT}
      - BOT_TOKEN=${BOT_TOKEN}
      - LOADING_VIDEO_ID=${LOADING_VIDEO_ID}
      - ANIMATION_FILE_ID=${ANIMATION_FILE_ID}
      - DEVELOPER_CHAT_ID=${DEVELOPER_CHAT_ID}
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn
