version: "3.9"

services:
  telegram_vpn:
    image: ghcr.io/wfg/openvpn-client
    container_name: telegram_vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./vpn/:/data/vpn
    restart: unless-stopped
    environment:
      VPN_CONFIG_PATTERN: "*.ovpn"
    healthcheck:
      test: ["CMD", "nslookup", "google.com", "8.8.8.8"]
      timeout: 10s
      interval: 10s
      retries: 3

  telegram:
    container_name: telegram
    image: ghcr.io/volkovskiyda/telegram-bot-api
    restart: unless-stopped
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    depends_on:
      telegram_vpn:
        condition: service_healthy
    network_mode: "service:telegram_vpn"

  dasovbot:
    container_name: dasovbot
    image: ghcr.io/volkovskiyda/dasovbot
    restart: unless-stopped
    environment:
      - BASE_URL=${BASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - LOADING_VIDEO_ID=${LOADING_VIDEO_ID}
      - DEVELOPER_CHAT_ID=${DEVELOPER_CHAT_ID}
    depends_on:
      telegram_vpn:
        condition: service_healthy
    network_mode: "service:telegram_vpn"
