services:
  vpn:
    image: ghcr.io/wfg/openvpn-client
    container_name: dasovbot_vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./vpn/:/data/vpn
    restart: unless-stopped
    environment:
      VPN_CONFIG_PATTERN: "*.ovpn"
    healthcheck:
      test: ["CMD", "nslookup", "google.com", "8.8.8.8"]
      timeout: 10s
      interval: 10s
      retries: 3

  api:
    container_name: dasovbot_api
    image: ghcr.io/volkovskiyda/telegram-bot-api
    restart: unless-stopped
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn

  bot:
    container_name: dasovbot
    image: ghcr.io/volkovskiyda/dasovbot
    restart: unless-stopped
    volumes:
      - ./config/:/project/config
    environment:
      - BASE_URL=${BASE_URL}
      - READ_TIMEOUT=${READ_TIMEOUT}
      - BOT_TOKEN=${BOT_TOKEN}
      - LOADING_VIDEO_ID=${LOADING_VIDEO_ID}
      - ANIMATION_FILE_ID=${ANIMATION_FILE_ID}
      - DEVELOPER_CHAT_ID=${DEVELOPER_CHAT_ID}
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn
